git:
  depth: false
language: java
dist: bionic
sudo: false
jdk:
- openjdk11
env:
  global:
  - GH_NAME='ga4gh-bot'
  - GH_EMAIL='ga4ghdev@gmail.com'
  - GH_ORG=jb-adams
  - GH_REPO=travis-tests
  - GH_BRANCH=gh-pages
  - GH_URL=https://raw.githubusercontent.com
  - FILE_TO_VALIDATE=service-registry.yaml
  - URL_TO_VALIDATE=$GH_URL/${TRAVIS_PULL_REQUEST_SLUG:-$TRAVIS_REPO_SLUG}/${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}/$FILE_TO_VALIDATE
  - secure: ggQ9A5v926RLSywyOxGi4algeNn7tZXGjvdeOfB5LhDANvRC9bqr+duHWmMf6Ueyd+Ncb2Uws+5RD+KfaQggBKxVS04S52YumXVRdObXdvsh17qGCp3dh20g+hP/ZWoKWpNARl1bc6vTlcM2GnIQZT7mXbjrRV94QjlPyLL2Lyuq07CfExxWetwscuVgMEpgjOUKGSlTqTWuU62kPvC2XyBHCKHDEXPpStX6yUlhItJFCZCUzlHFxQ8rD/MHDLFIpqgzOIO41sbCjLI5qmxGrAIFGBuhlE5UNrpr9QRrKlNPPqeXvUhRE6AeJQCD4SeBBdXqTtVvSp+3U3BHowZ8Bwv+ASXFMnWAagFdyNBGsmTSOo3aw46nEXhfU8gtFMfSlyQmvI3hfeK6ioc9jx6OFO+xa0e9EK+XVRo6MaOTUjyJIaevLIwRzGiUG77OqpjFcImpgst5mqwzvS8RDYJIWDcehwORAUTeZ/kULAOs+Y3hz0FNgwv4Dk86DLX8uKlTYmG0jCcgddvVZQ/RcqDMEiWL6Gp1P+y7fJapf/qY9Zo9Ej9F2O5mhk+9xkpd2Xsvwr9MriG7vBmyUNbDCdkcev/u1ZR3nqlmpZ+VC/Shq07MvUof786S4FyDCgZ7WKu7nQL7AdtnoZH3YC/J2BD2T/Qrb/URG9CWsIiLwvmRX9I=
before_install:
- git clone --branch=v1.1.0 https://github.com/mcupak/oas-validator.git
script:
- ./oas-validator/validate.sh "$URL_TO_VALIDATE"
after_success:
- chmod 755 ./scripts/build-and-push-docs.sh
- "./scripts/build-and-push-docs.sh"
